;
; File generated by cc65 v 2.19 - Git 1e1e8a6
;
	.fopt		compiler,"cc65 v 2.19 - Git 1e1e8a6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "lib/core-support/entity.c", 622, 1774983116
	.dbg		file, "lib/core-support/entity.h", 1099, 1774983116
	.dbg		file, "./lib/util/util_structs.h", 1400, 1774983116
	.dbg		file, "C:\cc65\include/stdint.h", 5720, 1767575976
	.dbg		file, "./lib/util/transform.h", 1139, 1774983116
	.dbg		file, "C:\cc65\include/stddef.h", 3037, 1767575976
	.export		_entityConstructor
	.export		_default_OnCollision

; ---------------------------------------------------------------
; enum STATUS __near__ entityConstructor (struct Entity *thisEntity, enum STATUS (*frameTask)(struct Entity *), enum STATUS (*renderer)(struct Entity *))
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_entityConstructor: near

	.dbg	func, "entityConstructor", "00", static, "_entityConstructor"
	.dbg	sym, "thisEntity", "00", auto, 4
	.dbg	sym, "frameTask", "00", auto, 2
	.dbg	sym, "renderer", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "lib/core-support/entity.c", 6
	jsr     pushax
;
; thisEntity->_worldCoords.x = 0;
;
	.dbg	line, "lib/core-support/entity.c", 7
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0E
	jsr     staxspidx
;
; thisEntity->_worldCoords.y = 0;
;
	.dbg	line, "lib/core-support/entity.c", 8
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$10
	jsr     staxspidx
;
; thisEntity->entityData = NULL;
;
	.dbg	line, "lib/core-support/entity.c", 9
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$06
	jsr     staxspidx
;
; thisEntity->childEntity = NULL;
;
	.dbg	line, "lib/core-support/entity.c", 10
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxspidx
;
; thisEntity->frameTask = frameTask;
;
	.dbg	line, "lib/core-support/entity.c", 11
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     staxspidx
;
; thisEntity->renderer = renderer;
;
	.dbg	line, "lib/core-support/entity.c", 12
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$02
	jsr     staxspidx
;
; return PASS;
;
	.dbg	line, "lib/core-support/entity.c", 17
	ldx     #$00
	lda     #$00
	jmp     L0001
;
; };
;
	.dbg	line, "lib/core-support/entity.c", 18
L0001:	jsr     incsp6
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ default_OnCollision (struct Entity *thisEntity, struct Entity *otherEntity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_default_OnCollision: near

	.dbg	func, "default_OnCollision", "00", static, "_default_OnCollision"
	.dbg	sym, "thisEntity", "00", auto, 2
	.dbg	sym, "otherEntity", "00", auto, 0

.segment	"CODE"

;
; struct Entity* otherEntity){
;
	.dbg	line, "lib/core-support/entity.c", 21
	jsr     pushax
;
; return;
;
	.dbg	line, "lib/core-support/entity.c", 23
	jmp     L0001
;
; };
;
	.dbg	line, "lib/core-support/entity.c", 24
L0001:	jsr     incsp4
	rts

	.dbg	line
.endproc

