;
; File generated by cc65 v 2.19 - Git 1e1e8a6
;
	.fopt		compiler,"cc65 v 2.19 - Git 1e1e8a6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "main.c", 1024, 1774983116
	.dbg		file, "C:\cc65\include/stdio.h", 6999, 1767575976
	.dbg		file, "C:\cc65\include/unistd.h", 4340, 1767575976
	.dbg		file, "core/engine.h", 485, 1774983116
	.dbg		file, "C:\cc65\include/atari.h", 22152, 1767575976
	.dbg		file, "C:\cc65\include/_atarios.h", 40084, 1767575976
	.dbg		file, "C:\cc65\include/_gtia.h", 13839, 1767575976
	.dbg		file, "C:\cc65\include/_pbi.h", 3143, 1767575976
	.dbg		file, "C:\cc65\include/_pokey.h", 11376, 1767575976
	.dbg		file, "C:\cc65\include/_pia.h", 3044, 1767575976
	.dbg		file, "C:\cc65\include/_antic.h", 11827, 1767575976
	.dbg		file, "C:\cc65\include/joystick.h", 5141, 1767575976
	.dbg		file, "C:\cc65\include/target.h", 3090, 1767575976
	.dbg		file, "core/../core-gfx/gfx.h", 1289, 1774983116
	.dbg		file, "C:\cc65\include/stdlib.h", 6948, 1767575976
	.dbg		file, "core/../core-gfx/antic-gtia/charmap.h", 194, 1774983116
	.dbg		file, "./lib/util/util_structs.h", 1400, 1774983116
	.dbg		file, "C:\cc65\include/stdint.h", 5720, 1767575976
	.dbg		file, "core/../core-gfx/antic-gtia/displaylist.h", 2173, 1774983116
	.dbg		file, "core/../core-gfx/antic-gtia/pmg.h", 2014, 1774983116
	.dbg		file, "C:\cc65\include/string.h", 5678, 1767575976
	.dbg		file, "C:\cc65\include/stdbool.h", 2506, 1767575976
	.dbg		file, "./lib/util/sprite.h", 496, 1774983116
	.dbg		file, "core/../core-gfx/gamemap.h", 435, 1774983116
	.dbg		file, "core/sound.h", 846, 1774983116
	.dbg		file, "core/../adventure-entities/player.h", 1301, 1774983116
	.dbg		file, "./lib/util/util.h", 840, 1774983116
	.dbg		file, "C:\cc65\include/stddef.h", 3037, 1767575976
	.dbg		file, "C:\cc65\include/peekpoke.h", 3108, 1767575976
	.dbg		file, "./lib/util/util_input.h", 361, 1774983116
	.dbg		file, "./lib/core-support/entity.h", 1099, 1774983116
	.dbg		file, "./lib/util/transform.h", 1139, 1774983116
	.dbg		file, "./lib/core-support/camera.h", 2032, 1774983116
	.dbg		file, "./lib/core-support/../../core-gfx/gfx.h", 1289, 1774983116
	.dbg		file, "core/../adventure-entities/items/items.h", 1082, 1774983116
	.dbg		file, "core/../adventure-entities/items/../../core/sound.h", 846, 1774983116
	.dbg		file, "core/../adventure-entities/../core-gfx/antic-gtia/pmg.h", 2014, 1774983116
	.dbg		file, "core/../adventure-entities/dragon.h", 1263, 1774983116
	.dbg		file, "core/../adventure-entities/map-interactables/orb.h", 532, 1774983116
	.forceimport	__STARTUP__
	.dbg		sym, "stdout", "00", extern, "_stdout"
	.import		_stdout
	.import		_freopen
	.import		_waitvsync
	.import		_engine_Boot
	.import		_engine_StateUpdate
	.import		_engine_Render
	.import		_engine_EventDispatcher
	.export		_debug_autoMove
	.export		_dir
	.export		_zeroVec
	.export		_main

.segment	"DATA"

_dir:
	.word	$0001
	.word	$0001
_zeroVec:
	.word	$0000
	.word	$0000

.segment	"RODATA"

S0001:
	.byte	$50,$31,$3A,$00
S0002:
	.byte	$77,$00

; ---------------------------------------------------------------
; void __near__ debug_autoMove (struct Transform *toMove)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_debug_autoMove: near

	.dbg	func, "debug_autoMove", "00", static, "_debug_autoMove"
	.dbg	sym, "toMove", "00", auto, 0

.segment	"CODE"

;
; void debug_autoMove(Transform *toMove){
;
	.dbg	line, "main.c", 52
	jsr     pushax
;
; dir.x = ((toMove->worldCoords.x > 312) 
;
	.dbg	line, "main.c", 53
	ldy     #$01
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	cmp     #$39
	txa
	sbc     #$01
	bvs     L0002
	eor     #$80
L0002:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
;
; || (toMove->worldCoords.x < 8)) ? -dir.x : dir.x;
;
	.dbg	line, "main.c", 54
	jne     L0003
	ldy     #$01
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	cmp     #$08
	txa
	sbc     #$00
	bvc     L0004
	eor     #$80
L0004:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0003
	ldx     #$00
	lda     #$00
	jeq     L0005
L0003:	ldx     #$00
	lda     #$01
L0005:	jeq     L0006
	lda     _dir
	ldx     _dir+1
	jsr     negax
	jmp     L0007
L0006:	lda     _dir
	ldx     _dir+1
L0007:	sta     _dir
	stx     _dir+1
;
; toMove->worldCoords.x += dir.x;
;
	.dbg	line, "main.c", 55
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     _dir
	ldx     _dir+1
	jsr     tosaddax
	ldy     #$04
	jsr     staxspidx
;
; }
;
	.dbg	line, "main.c", 56
	jsr     incsp2
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

;
; freopen("P1:", "w", stdout);
;
	.dbg	line, "main.c", 20
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	lda     _stdout
	ldx     _stdout+1
	jsr     _freopen
;
; engine_Boot();
;
	.dbg	line, "main.c", 24
	jsr     _engine_Boot
;
; while (true) {
;
	.dbg	line, "main.c", 27
	jmp     L0004
;
; engine_StateUpdate();
;
	.dbg	line, "main.c", 32
L0002:	jsr     _engine_StateUpdate
;
; waitvsync();
;
	.dbg	line, "main.c", 37
	jsr     _waitvsync
;
; engine_Render();
;
	.dbg	line, "main.c", 38
	jsr     _engine_Render
;
; engine_EventDispatcher();
;
	.dbg	line, "main.c", 41
	jsr     _engine_EventDispatcher
;
; while (true) {
;
	.dbg	line, "main.c", 27
L0004:	jmp     L0002
;
; }
;
	.dbg	line, "main.c", 45
	rts

	.dbg	line
.endproc

