;
; File generated by cc65 v 2.19 - Git 1e1e8a6
;
	.fopt		compiler,"cc65 v 2.19 - Git 1e1e8a6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "player.c", 2766, 1771024885
	.dbg		file, "util.h", 518, 1771024885
	.dbg		file, "C:\cc65\include/stddef.h", 3037, 1767575976
	.dbg		file, "C:\cc65\include/atari.h", 22152, 1767575976
	.dbg		file, "C:\cc65\include/_atarios.h", 40084, 1767575976
	.dbg		file, "C:\cc65\include/_gtia.h", 13839, 1767575976
	.dbg		file, "C:\cc65\include/_pbi.h", 3143, 1767575976
	.dbg		file, "C:\cc65\include/_pokey.h", 11376, 1767575976
	.dbg		file, "C:\cc65\include/_pia.h", 3044, 1767575976
	.dbg		file, "C:\cc65\include/_antic.h", 11827, 1767575976
	.dbg		file, "C:\cc65\include/peekpoke.h", 3108, 1767575976
	.dbg		file, "util_structs.h", 364, 1771024885
	.dbg		file, "player.h", 1264, 1771024885
	.dbg		file, "entity.h", 1061, 1771024885
	.dbg		file, "C:\cc65\include/joystick.h", 5141, 1767575976
	.dbg		file, "C:\cc65\include/target.h", 3090, 1767575976
	.dbg		file, "util_input.h", 190, 1771024885
	.dbg		file, "C:\cc65\include/assert.h", 3002, 1767575976
	.dbg		file, "items.h", 784, 1771024885
	.dbg		sym, "playerEnt", "00", extern, "_playerEnt"
	.import		_entityConstructor
	.import		_joy_read
	.export		_playerRoutine
	.export		_playerRenderer
	.export		_playerInputProcess
	.export		_playerConstructor
	.export		_nullItem
	.export		_nullItem_Task
	.export		_nullItem_renderer
	.export		_nullItem_constructor
	.import		_playerEnt

.segment	"BSS"

_nullItem:
	.res	10,$00

; ---------------------------------------------------------------
; enum STATUS __near__ playerRoutine (struct Entity *thisEntity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_playerRoutine: near

	.dbg	func, "playerRoutine", "00", static, "_playerRoutine"
	.dbg	sym, "thisEntity", "00", auto, 0

.segment	"CODE"

;
; STATUS playerRoutine(Entity* thisEntity) {
;
	.dbg	line, "player.c", 12
	jsr     pushax
;
; return playerInputProcess();
;
	.dbg	line, "player.c", 20
	jsr     _playerInputProcess
;
; }
;
	.dbg	line, "player.c", 21
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; enum STATUS __near__ playerRenderer (struct Entity *thisEntity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_playerRenderer: near

	.dbg	func, "playerRenderer", "00", static, "_playerRenderer"
	.dbg	sym, "thisEntity", "00", auto, 0

.segment	"CODE"

;
; STATUS playerRenderer(Entity* thisEntity) {
;
	.dbg	line, "player.c", 26
	jsr     pushax
;
; return UNDEFINED;
;
	.dbg	line, "player.c", 27
	ldx     #$00
	lda     #$01
;
; }
;
	.dbg	line, "player.c", 28
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; enum STATUS __near__ playerInputProcess (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_playerInputProcess: near

	.dbg	func, "playerInputProcess", "00", static, "_playerInputProcess"

.segment	"CODE"

;
; lastFrameState = joystickState;
;
	.dbg	line, "player.c", 36
	lda     M0001
	sta     M0002
;
; joystickState = joy_read(JOY_1);
;
	.dbg	line, "player.c", 38
	lda     #$00
	jsr     _joy_read
	sta     M0001
;
; if(JOY_RIGHT(joystickState)){
;
	.dbg	line, "player.c", 54
	and     #$08
	beq     L000C
;
; playerEnt.playerVelocity.x = playerEnt.playerSpeed;
;
	.dbg	line, "player.c", 55
	lda     _playerEnt+4
	ldx     _playerEnt+4+1
	sta     _playerEnt
	stx     _playerEnt+1
;
; playerEnt.playerEntity.eyeCoords.x += playerEnt.playerVelocity.x;
;
	.dbg	line, "player.c", 56
	clc
	adc     _playerEnt+12
	sta     _playerEnt+12
	txa
	adc     _playerEnt+12+1
	sta     _playerEnt+12+1
;
; } else if (JOY_LEFT(joystickState)){
;
	.dbg	line, "player.c", 57
	jmp     L0005
L000C:	lda     M0001
	and     #$04
	beq     L000E
;
; playerEnt.playerVelocity.x = playerEnt.playerSpeed;
;
	.dbg	line, "player.c", 58
	lda     _playerEnt+4
	ldx     _playerEnt+4+1
	sta     _playerEnt
	stx     _playerEnt+1
;
; playerEnt.playerEntity.eyeCoords.x -= playerEnt.playerVelocity.x;
;
	.dbg	line, "player.c", 59
	eor     #$FF
	sec
	adc     _playerEnt+12
	sta     _playerEnt+12
	txa
	eor     #$FF
	adc     _playerEnt+12+1
	sta     _playerEnt+12+1
;
; } else {
;
	.dbg	line, "player.c", 60
	jmp     L0005
;
; playerEnt.playerVelocity.x = 0;
;
	.dbg	line, "player.c", 61
L000E:	sta     _playerEnt
	sta     _playerEnt+1
;
; if(JOY_UP(joystickState)){
;
	.dbg	line, "player.c", 64
L0005:	lda     M0001
	and     #$01
	beq     L0006
;
; playerEnt.playerVelocity.y = playerEnt.playerSpeed;
;
	.dbg	line, "player.c", 65
	lda     _playerEnt+4+1
	sta     _playerEnt+2+1
	lda     _playerEnt+4
	sta     _playerEnt+2
;
; } else {
;
	.dbg	line, "player.c", 66
	jmp     L000F
;
; playerEnt.playerVelocity.y = -playerEnt.playerSpeed * JOY_DOWN(joystickState);
;
	.dbg	line, "player.c", 67
L0006:	lda     _playerEnt+4
	ldx     _playerEnt+4+1
	jsr     negax
	jsr     pushax
	lda     M0001
	and     #$02
	jsr     tosmula0
	sta     _playerEnt+2
	stx     _playerEnt+2+1
;
; if(JOY_FIRE(joystickState) && !JOY_FIRE(lastFrameState)){
;
	.dbg	line, "player.c", 72
L000F:	lda     M0001
	and     #$10
	beq     L0008
	lda     M0002
	and     #$10
	bne     L0008
;
; playerEnt.playerEntity.childEntity->frameTask(playerEnt.playerEntity.childEntity);
;
	.dbg	line, "player.c", 74
	lda     _playerEnt+10
	ldx     _playerEnt+10+1
	jsr     pushw
	lda     _playerEnt+10
	ldx     _playerEnt+10+1
	pha
	ldy     #$00
	lda     (c_sp),y
	sta     jmpvec+1
	iny
	lda     (c_sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
;
; playerEnt.playerEntity.eyeCoords.y += playerEnt.playerVelocity.y;
;
	.dbg	line, "player.c", 81
L0008:	lda     _playerEnt+2
	clc
	adc     _playerEnt+14
	sta     _playerEnt+14
	lda     _playerEnt+2+1
	adc     _playerEnt+14+1
	sta     _playerEnt+14+1
;
; return PASS;
;
	.dbg	line, "player.c", 82
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "player.c", 83
	rts

	.dbg	line
.segment	"DATA"

M0001:
	.byte	$00

.segment	"BSS"

M0002:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; enum STATUS __near__ playerConstructor (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_playerConstructor: near

	.dbg	func, "playerConstructor", "00", static, "_playerConstructor"

.segment	"CODE"

;
; playerEnt.playerSpeed = 1;
;
	.dbg	line, "player.c", 87
	ldx     #$00
	lda     #$01
	sta     _playerEnt+4
	stx     _playerEnt+4+1
;
; playerEnt.playerVelocity.x = 0;
;
	.dbg	line, "player.c", 88
	txa
	sta     _playerEnt
	sta     _playerEnt+1
;
; playerEnt.playerVelocity.y = 0;
;
	.dbg	line, "player.c", 89
	sta     _playerEnt+2
	sta     _playerEnt+2+1
;
; playerEnt.playerEntity.childEntity = &nullItem;
;
	.dbg	line, "player.c", 100
	lda     #>(_nullItem)
	sta     _playerEnt+10+1
	lda     #<(_nullItem)
	sta     _playerEnt+10
;
; nullItem_constructor(&nullItem);  
;
	.dbg	line, "player.c", 103
	lda     #<(_nullItem)
	ldx     #>(_nullItem)
	jsr     _nullItem_constructor
;
; return PASS;
;
	.dbg	line, "player.c", 105
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "player.c", 106
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; enum STATUS __near__ nullItem_Task (struct Entity *thisEntity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_nullItem_Task: near

	.dbg	func, "nullItem_Task", "00", static, "_nullItem_Task"
	.dbg	sym, "thisEntity", "00", auto, 0

.segment	"CODE"

;
; STATUS nullItem_Task(Entity* thisEntity) { return UNDEFINED; };
;
	.dbg	line, "items.h", 18
	jsr     pushax
	ldx     #$00
	lda     #$01
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; enum STATUS __near__ nullItem_renderer (struct Entity *thisEntity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_nullItem_renderer: near

	.dbg	func, "nullItem_renderer", "00", static, "_nullItem_renderer"
	.dbg	sym, "thisEntity", "00", auto, 0

.segment	"CODE"

;
; STATUS nullItem_renderer(Entity* thisEntity) { return UNDEFINED; };
;
	.dbg	line, "items.h", 19
	jsr     pushax
	ldx     #$00
	lda     #$01
	jmp     incsp2

	.dbg	line
.endproc

; ---------------------------------------------------------------
; enum STATUS __near__ nullItem_constructor (struct Entity *thisEntity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_nullItem_constructor: near

	.dbg	func, "nullItem_constructor", "00", static, "_nullItem_constructor"
	.dbg	sym, "thisEntity", "00", auto, 0

.segment	"CODE"

;
; STATUS nullItem_constructor(Entity* thisEntity) {
;
	.dbg	line, "items.h", 24
	jsr     pushax
;
; return entityConstructor(&nullItem, nullItem_Task, nullItem_renderer);
;
	.dbg	line, "items.h", 25
	lda     #<(_nullItem)
	ldx     #>(_nullItem)
	jsr     pushax
	lda     #<(_nullItem_Task)
	ldx     #>(_nullItem_Task)
	jsr     pushax
	lda     #<(_nullItem_renderer)
	ldx     #>(_nullItem_renderer)
	jsr     _entityConstructor
;
; };
;
	.dbg	line, "items.h", 26
	jmp     incsp2

	.dbg	line
.endproc

