;
; File generated by cc65 v 2.19 - Git 1e1e8a6
;
	.fopt		compiler,"cc65 v 2.19 - Git 1e1e8a6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "lib/util/util.c", 1262, 1774983116
	.dbg		file, "lib/util/util.h", 840, 1774983116
	.dbg		file, "C:\cc65\include/stddef.h", 3037, 1767575976
	.dbg		file, "C:\cc65\include/atari.h", 22152, 1767575976
	.dbg		file, "C:\cc65\include/_atarios.h", 40084, 1767575976
	.dbg		file, "C:\cc65\include/_gtia.h", 13839, 1767575976
	.dbg		file, "C:\cc65\include/_pbi.h", 3143, 1767575976
	.dbg		file, "C:\cc65\include/_pokey.h", 11376, 1767575976
	.dbg		file, "C:\cc65\include/_pia.h", 3044, 1767575976
	.dbg		file, "C:\cc65\include/_antic.h", 11827, 1767575976
	.dbg		file, "C:\cc65\include/peekpoke.h", 3108, 1767575976
	.export		_clamp_int
	.export		_memZero
	.export		_clamp_char
	.export		_max
	.export		_min
	.export		_reverse_char

; ---------------------------------------------------------------
; unsigned int __near__ clamp_int (unsigned int value, unsigned int min, unsigned int max)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clamp_int: near

	.dbg	func, "clamp_int", "00", static, "_clamp_int"
	.dbg	sym, "value", "00", auto, 4
	.dbg	sym, "min", "00", auto, 2
	.dbg	sym, "max", "00", auto, 0

.segment	"CODE"

;
; unsigned int clamp_int(unsigned int value,unsigned int min,unsigned int max) {
;
	.dbg	line, "lib/util/util.c", 3
	jsr     pushax
;
; if (value < min) {
;
	.dbg	line, "lib/util/util.c", 4
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosultax
	jeq     L0002
;
; return min;
;
	.dbg	line, "lib/util/util.c", 5
	ldy     #$03
	jsr     ldaxysp
	jmp     L0001
;
; } else if (value > max) {
;
	.dbg	line, "lib/util/util.c", 6
	jmp     L0004
L0002:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosugtax
	jeq     L0004
;
; return max;
;
	.dbg	line, "lib/util/util.c", 7
	ldy     #$01
	jsr     ldaxysp
	jmp     L0001
;
; return value;
;
	.dbg	line, "lib/util/util.c", 9
L0004:	ldy     #$05
	jsr     ldaxysp
	jmp     L0001
;
; }
;
	.dbg	line, "lib/util/util.c", 10
L0001:	jsr     incsp6
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ memZero (unsigned int start, unsigned int offset)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_memZero: near

	.dbg	func, "memZero", "00", static, "_memZero"
	.dbg	sym, "start", "00", auto, 2
	.dbg	sym, "offset", "00", auto, 0
	.dbg	sym, "x", "00", auto, -2

.segment	"CODE"

;
; void memZero(unsigned int start, unsigned int offset) {
;
	.dbg	line, "lib/util/util.c", 23
	jsr     pushax
;
; int x = 0;
;
	.dbg	line, "lib/util/util.c", 24
	ldx     #$00
	lda     #$00
	jsr     pushax
;
; for (x = 0; x < offset; x++) {
;
	.dbg	line, "lib/util/util.c", 25
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0002:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosultax
	jne     L0005
	jmp     L0003
;
; POKE(start + x,0);
;
	.dbg	line, "lib/util/util.c", 26
L0005:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
;
; for (x = 0; x < offset; x++) {
;
	.dbg	line, "lib/util/util.c", 25
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
;
; }
;
	.dbg	line, "lib/util/util.c", 28
L0003:	jsr     incsp6
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ clamp_char (unsigned char value, unsigned char min, unsigned char max)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clamp_char: near

	.dbg	func, "clamp_char", "00", static, "_clamp_char"
	.dbg	sym, "value", "00", auto, 2
	.dbg	sym, "min", "00", auto, 1
	.dbg	sym, "max", "00", auto, 0

.segment	"CODE"

;
; unsigned char clamp_char(unsigned char value,unsigned char min,unsigned char max) {
;
	.dbg	line, "lib/util/util.c", 13
	jsr     pusha
;
; if (value < min) {
;
	.dbg	line, "lib/util/util.c", 14
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	jsr     tosultax
	jeq     L0002
;
; return min;
;
	.dbg	line, "lib/util/util.c", 15
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	jmp     L0001
;
; } else if (value > max) {
;
	.dbg	line, "lib/util/util.c", 16
	jmp     L0004
L0002:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     tosugtax
	jeq     L0004
;
; return max;
;
	.dbg	line, "lib/util/util.c", 17
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	jmp     L0001
;
; return value;
;
	.dbg	line, "lib/util/util.c", 19
L0004:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jmp     L0001
;
; }
;
	.dbg	line, "lib/util/util.c", 20
L0001:	jsr     incsp3
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned int __near__ max (unsigned int a, unsigned int b)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_max: near

	.dbg	func, "max", "00", static, "_max"
	.dbg	sym, "a", "00", auto, 2
	.dbg	sym, "b", "00", auto, 0

.segment	"CODE"

;
; unsigned int max(unsigned int a, unsigned int b) {
;
	.dbg	line, "lib/util/util.c", 30
	jsr     pushax
;
; if (a >= b) {
;
	.dbg	line, "lib/util/util.c", 31
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosugeax
	jeq     L0002
;
; return a;
;
	.dbg	line, "lib/util/util.c", 32
	ldy     #$03
	jsr     ldaxysp
	jmp     L0001
;
; return b;
;
	.dbg	line, "lib/util/util.c", 34
L0002:	ldy     #$01
	jsr     ldaxysp
	jmp     L0001
;
; }
;
	.dbg	line, "lib/util/util.c", 35
L0001:	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned int __near__ min (unsigned int a, unsigned int b)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_min: near

	.dbg	func, "min", "00", static, "_min"
	.dbg	sym, "a", "00", auto, 2
	.dbg	sym, "b", "00", auto, 0

.segment	"CODE"

;
; unsigned int min(unsigned int a,unsigned int b) {
;
	.dbg	line, "lib/util/util.c", 37
	jsr     pushax
;
; if (a <= b) {
;
	.dbg	line, "lib/util/util.c", 38
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosuleax
	jeq     L0002
;
; return a;
;
	.dbg	line, "lib/util/util.c", 39
	ldy     #$03
	jsr     ldaxysp
	jmp     L0001
;
; return b;
;
	.dbg	line, "lib/util/util.c", 41
L0002:	ldy     #$01
	jsr     ldaxysp
	jmp     L0001
;
; }
;
	.dbg	line, "lib/util/util.c", 42
L0001:	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ reverse_char (unsigned char c)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_reverse_char: near

	.dbg	func, "reverse_char", "00", static, "_reverse_char"
	.dbg	sym, "c", "00", auto, 0

.segment	"CODE"

;
; unsigned char reverse_char(unsigned char c) {
;
	.dbg	line, "lib/util/util.c", 46
	jsr     pusha
;
; c = (c & 0xF0) >> 4 | (c & 0x0F) << 4;
;
	.dbg	line, "lib/util/util.c", 47
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$F0
	jsr     asrax4
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$0F
	jsr     aslax4
	jsr     tosorax
	ldx     #$00
	ldy     #$00
	sta     (c_sp),y
;
; c = (c & 0xCC) >> 2 | (c & 0x33) << 2;
;
	.dbg	line, "lib/util/util.c", 48
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$CC
	jsr     asrax2
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$33
	jsr     aslax2
	jsr     tosorax
	ldx     #$00
	ldy     #$00
	sta     (c_sp),y
;
; c = (c & 0xAA) >> 1 | (c & 0x55) << 1;
;
	.dbg	line, "lib/util/util.c", 49
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$AA
	jsr     asrax1
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$55
	jsr     aslax1
	jsr     tosorax
	ldx     #$00
	ldy     #$00
	sta     (c_sp),y
;
; return c;
;
	.dbg	line, "lib/util/util.c", 50
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	jmp     L0001
;
; }
;
	.dbg	line, "lib/util/util.c", 51
L0001:	jsr     incsp1
	rts

	.dbg	line
.endproc

